import { supabase } from "@/integrations/supabase/client";
import { reminderService } from "./reminderService";
import { bookingService } from "./bookingService";

export const reminderBackfillService = {
  /**
   * Backfill reminders for all existing bookings that don't have reminders yet
   */
  async backfillAllBookingReminders(): Promise<{
    success: number;
    failed: number;
    skipped: number;
    errors: string[];
  }> {
    const results = {
      success: 0,
      failed: 0,
      skipped: 0,
      errors: [] as string[]
    };

    try {
      console.log("Starting reminder backfill for all bookings...");

      // Get all bookings
      const bookings = await bookingService.getAllBookings();
      console.log(`Found ${bookings.length} bookings to process`);

      for (const booking of bookings) {
        try {
          // Check if this booking already has reminders
          const { data: existingReminders, error: checkError } = await supabase
            .from("reminders")
            .select("id")
            .eq("booking_id", booking.id)
            .eq("auto_generated", true);

          if (checkError) {
            console.error(`Error checking reminders for booking ${booking.id}:`, checkError);
            results.failed++;
            results.errors.push(`${booking.name}: ${checkError.message}`);
            continue;
          }

          // Skip if reminders already exist
          if (existingReminders && existingReminders.length > 0) {
            console.log(`Skipping ${booking.name} - already has ${existingReminders.length} reminders`);
            results.skipped++;
            continue;
          }

          // Generate reminders for this booking
          await reminderService.generateBookingReminders(booking.id, {
            eventName: booking.name,
            contactName: booking.contact_name,
            startDate: new Date(booking.start_date),
            isPending: !booking.confirmed
          });

          console.log(`✓ Generated reminders for: ${booking.name}`);
          results.success++;
        } catch (error: any) {
          console.error(`Error processing booking ${booking.name}:`, error);
          results.failed++;
          results.errors.push(`${booking.name}: ${error.message}`);
        }
      }

      console.log("\n=== Backfill Complete ===");
      console.log(`Success: ${results.success}`);
      console.log(`Skipped: ${results.skipped}`);
      console.log(`Failed: ${results.failed}`);
      if (results.errors.length > 0) {
        console.log("\nErrors:");
        results.errors.forEach(err => console.log(`  - ${err}`));
      }

      return results;
    } catch (error: any) {
      console.error("Fatal error during backfill:", error);
      throw error;
    }
  },

  /**
   * Delete all auto-generated reminders (useful for testing/resetting)
   */
  async deleteAllAutoGeneratedReminders(): Promise<number> {
    try {
      const { data, error } = await supabase
        .from("reminders")
        .delete()
        .eq("auto_generated", true)
        .select();

      if (error) throw error;

      const count = data?.length || 0;
      console.log(`Deleted ${count} auto-generated reminders`);
      return count;
    } catch (error) {
      console.error("Error deleting auto-generated reminders:", error);
      throw error;
    }
  },

  /**
   * Get statistics about reminders in the system
   */
  async getReminderStats(): Promise<{
    total: number;
    autoGenerated: number;
    manual: number;
    byStatus: Record<string, number>;
    byCategory: Record<string, number>;
  }> {
    try {
      const { data: allReminders, error } = await supabase
        .from("reminders")
        .select("*");

      if (error) throw error;

      const stats = {
        total: allReminders?.length || 0,
        autoGenerated: 0,
        manual: 0,
        byStatus: {} as Record<string, number>,
        byCategory: {} as Record<string, number>
      };

      if (allReminders) {
        allReminders.forEach(reminder => {
          // Count auto vs manual
          if (reminder.auto_generated) {
            stats.autoGenerated++;
          } else {
            stats.manual++;
          }

          // Count by status
          const status = reminder.status || "unknown";
          stats.byStatus[status] = (stats.byStatus[status] || 0) + 1;

          // Count by category
          const category = reminder.category || "unknown";
          stats.byCategory[category] = (stats.byCategory[category] || 0) + 1;
        });
      }

      return stats;
    } catch (error) {
      console.error("Error getting reminder stats:", error);
      throw error;
    }
  }
};
