import { useState, useEffect } from "react";
import {
  Bell,
  X,
  Clock,
  Check,
  AlertCircle,
  Calendar,
  Mail,
  Wrench,
  UserCheck,
  Plus,
  Database as DatabaseIcon,
  Loader2,
  RefreshCw,
  CheckCircle2,
  Circle,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { format, isPast, isToday } from "date-fns";
import { reminderService } from "@/services/reminderService";
import type { Database } from "@/integrations/supabase/types";
import { useToast } from "@/hooks/use-toast";
import { reminderBackfillService } from "@/services/reminderBackfillService";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";

type Reminder = Database["public"]["Tables"]["reminders"]["Row"];

interface TaskSidebarProps {
  onCreateReminder: () => void;
  refreshTrigger?: number;
}

const categoryIcons = {
  booking: Calendar,
  maintenance: Wrench,
  follow_up: UserCheck,
  email: Mail,
  custom: AlertCircle,
};

const categoryColors = {
  booking: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300",
  maintenance:
    "bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-300",
  follow_up:
    "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300",
  email: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300",
  custom:
    "bg-slate-100 text-slate-700 dark:bg-slate-900/30 dark:text-slate-300",
};

const priorityColors = {
  high: "border-l-4 border-red-500",
  medium: "border-l-4 border-yellow-500",
  low: "border-l-4 border-blue-500",
};

export function TaskSidebar({
  onCreateReminder,
  refreshTrigger = 0,
}: TaskSidebarProps) {
  const [open, setOpen] = useState(false);
  const [activeTab, setActiveTab] = useState<"today" | "future">("today");
  const [todayReminders, setTodayReminders] = useState<Reminder[]>([]);
  const [futureReminders, setFutureReminders] = useState<Reminder[]>([]);
  const [loading, setLoading] = useState(false);
  const [urgentCount, setUrgentCount] = useState(0);

  const [backfillStats, setBackfillStats] = useState<{
    total: number;
    autoGenerated: number;
    manual: number;
  } | null>(null);
  const [backfillRunning, setBackfillRunning] = useState(false);
  const [backfillResults, setBackfillResults] = useState<{
    success: number;
    failed: number;
    skipped: number;
    errors: string[];
  } | null>(null);

  const { toast } = useToast();

  useEffect(() => {
    if (open) {
      loadReminders();
      loadStats();
    }
  }, [refreshTrigger, open]);

  useEffect(() => {
    // Check for urgent tasks every minute
    const interval = setInterval(checkUrgentTasks, 60000);
    return () => clearInterval(interval);
  }, [todayReminders]);

  const loadStats = async () => {
    try {
      const stats = await reminderBackfillService.getReminderStats();
      setBackfillStats(stats);
    } catch (error) {
      console.error("Error loading reminder stats:", error);
    }
  };

  const handleRunBackfill = async () => {
    if (backfillRunning) return;
    
    setBackfillRunning(true);
    setBackfillResults(null);
    
    try {
      const results = await reminderBackfillService.backfillAllBookingReminders();
      setBackfillResults(results);
      await loadReminders();
      await loadStats();
      
      toast({
        title: "Backfill Complete",
        description: `Successfully created reminders for ${results.success} bookings. ${results.skipped} already had reminders.`,
      });
    } catch (error: any) {
      console.error("Error running backfill:", error);
      toast({
        title: "Backfill Failed",
        description: error.message || "Failed to run backfill operation",
        variant: "destructive"
      });
    } finally {
      setBackfillRunning(false);
    }
  };


  const loadReminders = async () => {
    try {
      setLoading(true);
      const [today, overdue, future] = await Promise.all([
        reminderService.getTodayReminders(),
        reminderService.getOverdueReminders(),
        reminderService.getFutureReminders(),
      ]);

      const todayTasks = [...overdue, ...today];
      setTodayReminders(todayTasks);
      setFutureReminders(future);
      setUrgentCount(
        todayTasks.filter(
          (r) => r.priority === "high" || isPast(new Date(r.due_date))
        ).length
      );
    } catch (error) {
      console.error("Error loading reminders:", error);
    } finally {
      setLoading(false);
    }
  };

  const checkUrgentTasks = () => {
    const urgent = todayReminders.filter(
      (r) => r.priority === "high" || isPast(new Date(r.due_date))
    ).length;
    setUrgentCount(urgent);
  };

  const handleSnooze = async (reminderId: string, minutes: number) => {
    try {
      await reminderService.snoozeReminder(reminderId, minutes);
      toast({
        title: "Task Snoozed",
        description: `Reminder snoozed for ${minutes} minutes`,
      });
      await loadReminders();
    } catch (error) {
      console.error("Error snoozing reminder:", error);
      toast({
        title: "Error",
        description: "Failed to snooze reminder",
        variant: "destructive",
      });
    }
  };

  const handleDismiss = async (reminderId: string) => {
    try {
      await reminderService.dismissReminder(reminderId);
      toast({
        title: "Task Dismissed",
        description: "Reminder has been dismissed",
      });
      await loadReminders();
    } catch (error) {
      console.error("Error dismissing reminder:", error);
      toast({
        title: "Error",
        description: "Failed to dismiss reminder",
        variant: "destructive",
      });
    }
  };

  const handleComplete = async (reminderId: string) => {
    try {
      await reminderService.completeReminder(reminderId);
      toast({
        title: "Task Completed",
        description: "Great job! Task marked as complete",
        variant: "default",
      });
      await loadReminders();
    } catch (error) {
      console.error("Error completing reminder:", error);
      toast({
        title: "Error",
        description: "Failed to complete reminder",
        variant: "destructive",
      });
    }
  };

  const displayReminders =
    activeTab === "today" ? todayReminders : futureReminders;

  return (
    <>
      <Sheet open={open} onOpenChange={setOpen}>
        <SheetTrigger asChild>
          <div className="fixed bottom-6 right-6 z-50">
            <Button
              size="lg"
              className="h-14 w-14 rounded-full shadow-2xl bg-orange-600 hover:bg-orange-700 text-white relative"
            >
              <Bell className="h-6 w-6" />
              {urgentCount > 0 && (
                <span className="absolute -top-1 -right-1 h-6 w-6 bg-red-500 rounded-full flex items-center justify-center text-xs font-bold animate-pulse">
                  {urgentCount}
                </span>
              )}
            </Button>
          </div>
        </SheetTrigger>

        <SheetContent className="w-[400px] sm:w-[540px] overflow-y-auto p-0 flex flex-col">
          <SheetHeader className="p-6 bg-gradient-to-r from-orange-600 to-amber-600 text-white">
            <SheetTitle className="flex items-center gap-3 text-2xl font-bold text-white">
              <Bell className="h-6 w-6" />
              Task & Reminder Center
            </SheetTitle>
            <SheetDescription className="text-orange-100">
              Manage your tasks and set reminders for important events
            </SheetDescription>
          </SheetHeader>
          
          <div className="p-4 border-b border-stone-200 dark:border-stone-800 space-y-4">
            {/* Backfill Management Section */}
            <Card className="border-blue-200 dark:border-blue-800 bg-blue-50 dark:bg-blue-950/20">
              <CardHeader className="py-3">
                <CardTitle className="text-sm flex items-center gap-2">
                  <DatabaseIcon className="h-4 w-4 text-blue-600" />
                  Reminder System
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3 pt-0">
                {backfillStats && (
                  <div className="grid grid-cols-3 gap-2 text-center">
                    <div className="p-2 bg-white dark:bg-stone-900 rounded-lg">
                      <div className="text-2xl font-bold text-blue-600">{backfillStats.total}</div>
                      <div className="text-xs text-stone-600 dark:text-stone-400">Total</div>
                    </div>
                    <div className="p-2 bg-white dark:bg-stone-900 rounded-lg">
                      <div className="text-2xl font-bold text-green-600">{backfillStats.autoGenerated}</div>
                      <div className="text-xs text-stone-600 dark:text-stone-400">Auto</div>
                    </div>
                    <div className="p-2 bg-white dark:bg-stone-900 rounded-lg">
                      <div className="text-2xl font-bold text-purple-600">{backfillStats.manual}</div>
                      <div className="text-xs text-stone-600 dark:text-stone-400">Manual</div>
                    </div>
                  </div>
                )}
  
                <div className="space-y-2">
                  <Button
                    onClick={handleRunBackfill}
                    disabled={backfillRunning}
                    className="w-full bg-blue-600 hover:bg-blue-700"
                    size="sm"
                  >
                    {backfillRunning ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        Processing...
                      </>
                    ) : (
                      <>
                        <RefreshCw className="h-4 w-4 mr-2" />
                        Generate Reminders for All Events
                      </>
                    )}
                  </Button>
                  <p className="text-xs text-stone-600 dark:text-stone-400 text-center px-2">
                    Creates reminders for existing bookings that don't have them yet.
                  </p>
                </div>
  
                {backfillResults && (
                  <div className="p-3 bg-white dark:bg-stone-900 rounded-lg space-y-2">
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-green-600 dark:text-green-400">✓ Success:</span>
                      <span className="font-semibold">{backfillResults.success}</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-blue-600 dark:text-blue-400">⊙ Skipped:</span>
                      <span className="font-semibold">{backfillResults.skipped}</span>
                    </div>
                    {backfillResults.failed > 0 && (
                      <div className="flex items-center justify-between text-sm">
                        <span className="text-red-600 dark:text-red-400">✗ Failed:</span>
                        <span className="font-semibold">{backfillResults.failed}</span>
                      </div>
                    )}
                    {backfillResults.errors.length > 0 && (
                      <div className="mt-2 pt-2 border-t border-stone-200 dark:border-stone-700">
                        <p className="text-xs text-red-600 dark:text-red-400 font-semibold mb-1">Errors:</p>
                        <div className="max-h-20 overflow-y-auto text-xs text-stone-600 dark:text-stone-400 space-y-1">
                          {backfillResults.errors.map((err, idx) => (
                            <div key={idx}>• {err}</div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>

            <Button
              onClick={onCreateReminder}
              className="w-full bg-orange-600 hover:bg-orange-700"
            >
              <Plus className="h-4 w-4 mr-2" />
              Create Custom Reminder
            </Button>
          </div>

          <div className="flex-1 flex flex-col min-h-0">
            {/* Tabs */}
            <div className="flex border-b border-t border-stone-200 dark:border-stone-800 shrink-0">
              <button
                onClick={() => setActiveTab("today")}
                className={`flex-1 py-3 px-4 text-sm font-medium transition-colors ${
                  activeTab === "today"
                    ? "text-orange-600 border-b-2 border-orange-600 bg-orange-50 dark:bg-orange-950/20"
                    : "text-stone-600 dark:text-stone-400 hover:text-stone-900 dark:hover:text-stone-100"
                }`}
              >
                Today ({todayReminders.length})
              </button>
              <button
                onClick={() => setActiveTab("future")}
                className={`flex-1 py-3 px-4 text-sm font-medium transition-colors ${
                  activeTab === "future"
                    ? "text-orange-600 border-b-2 border-orange-600 bg-orange-50 dark:bg-orange-950/20"
                    : "text-stone-600 dark:text-stone-400 hover:text-stone-900 dark:hover:text-stone-100"
                }`}
              >
                Future ({futureReminders.length})
              </button>
            </div>
            
            {/* Task List */}
            <div className="flex-1 overflow-y-auto p-4 space-y-3">
              {loading ? (
                <div className="text-center py-12">
                  <Loader2 className="animate-spin h-8 w-8 text-orange-600 mx-auto mb-4" />
                  <p className="text-stone-600 dark:text-stone-400">Loading tasks...</p>
                </div>
              ) : displayReminders.length === 0 ? (
                <div className="text-center py-12">
                  <Bell className="h-16 w-16 mx-auto mb-4 text-stone-300 dark:text-stone-700" />
                  <h3 className="text-lg font-medium text-stone-900 dark:text-stone-100 mb-2">
                    {activeTab === "today" ? "All Clear!" : "No Future Tasks"}
                  </h3>
                  <p className="text-stone-600 dark:text-stone-400">
                    {activeTab === "today"
                      ? "No tasks due today. Create custom reminders to stay organized."
                      : "No upcoming tasks scheduled. All caught up!"}
                  </p>
                </div>
              ) : (
                displayReminders.map((reminder) => {
                  const CategoryIcon =
                    categoryIcons[reminder.category as keyof typeof categoryIcons];
                  const categoryColor =
                    categoryColors[reminder.category as keyof typeof categoryColors];
                  const priorityColor =
                    priorityColors[reminder.priority as keyof typeof priorityColors];
                  const isOverdue =
                    isPast(new Date(reminder.due_date)) &&
                    !isToday(new Date(reminder.due_date));

                  return (
                    <Card
                      key={reminder.id}
                      className={`${priorityColor} hover:shadow-lg transition-shadow ${
                        isOverdue ? "bg-red-50 dark:bg-red-950/20" : ""
                      }`}
                    >
                      <CardHeader className="pb-3">
                        <div className="flex items-start justify-between">
                          <div className="flex items-start gap-3 flex-1">
                            <div className={`p-2 rounded-lg ${categoryColor}`}>
                              <CategoryIcon className="h-4 w-4" />
                            </div>
                            <div className="flex-1 min-w-0">
                              <CardTitle className="text-sm font-semibold mb-1">
                                {reminder.title}
                              </CardTitle>
                              {reminder.description && (
                                <p className="text-xs text-stone-600 dark:text-stone-400 mb-2">
                                  {reminder.description}
                                </p>
                              )}
                              <div className="flex items-center gap-2 flex-wrap">
                                <Badge variant="outline" className="text-xs">
                                  {format(new Date(reminder.due_date), "h:mm a")}
                                </Badge>
                                {isOverdue && (
                                  <Badge variant="destructive" className="text-xs">
                                    Overdue!
                                  </Badge>
                                )}
                                {reminder.priority === "high" && (
                                  <Badge variant="destructive" className="text-xs">
                                    High Priority
                                  </Badge>
                                )}
                              </div>
                            </div>
                          </div>
                        </div>
                      </CardHeader>

                      <CardContent className="pt-0">
                        <div className="flex items-center gap-2">
                          <Button
                            onClick={() => handleComplete(reminder.id)}
                            size="sm"
                            variant="default"
                            className="flex-1 bg-green-600 hover:bg-green-700"
                          >
                            <Check className="h-3 w-3 mr-1" />
                            Complete
                          </Button>

                          <Select
                            onValueChange={(value) =>
                              handleSnooze(reminder.id, parseInt(value))
                            }
                          >
                            <SelectTrigger className="w-[110px] h-9">
                              <Clock className="h-3 w-3 mr-1" />
                              <span className="text-xs">Snooze</span>
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="15">15 minutes</SelectItem>
                              <SelectItem value="30">30 minutes</SelectItem>
                              <SelectItem value="60">1 hour</SelectItem>
                              <SelectItem value="120">2 hours</SelectItem>
                              <SelectItem value="240">4 hours</SelectItem>
                              <SelectItem value="1440">1 day</SelectItem>
                            </SelectContent>
                          </Select>

                          <Button
                            onClick={() => handleDismiss(reminder.id)}
                            size="sm"
                            variant="ghost"
                            className="text-red-600 hover:text-red-700 hover:bg-red-50 dark:hover:bg-red-950/20"
                          >
                            <X className="h-4 w-4" />
                          </Button>
                        </div>
                      </CardContent>
                    </Card>
                  );
                })
              )}
            </div>
          </div>
        </SheetContent>
      </Sheet>
    </>
  );
}
